"""
Model any concept through the fractal Qqci former.

Depth 1: the seven plane scores around Unity. The concept's position.
Depth 2: the 49 cells Qa.qb, read as "the b of the a". Generated, not authored.
Depth 3: the 343 cells, drilled on demand.

COMPOSITION RULE
----------------
The Kronecker structure fixes how depth-2 values follow from depth-1: the
depth-2 reading of a concept is its own vector composed with itself, so

    cell(a, b) = v_a * v_b

This is not a choice. It is what B (x) B does to a vector, and it means the
question set at every depth is GENERATED by the structure rather than written
by hand. Asking "what is the How of the Where of a house" is not a new
question requiring new data; it is a coordinate that already exists.

A consequence worth stating: R_net compounds with depth. If P is the product
of the seven depth-1 scores, then the product over all 49 depth-2 cells is
P^14, so R_net(depth 2) = R_net(depth 1)^14. Incoherence AMPLIFIES when you
drill. That is the formal justification for the staircase gate: drilling an
unfilled state does not merely waste effort, it explodes.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from fractal_basis import cell_address, generator, PLANE_NAMES
from vft import FieldMath, Idea, Judgement, MoralVectorDef, MoralVectors

VECTORS: List[MoralVectorDef] = [
    MoralVectors.WHO, MoralVectors.WHAT, MoralVectors.WHERE, MoralVectors.WHY,
    MoralVectors.HOW, MoralVectors.CAUSE, MoralVectors.EFFECT,
]
# Index order must match fractal_basis.PLANE_NAMES: Who What Where Why How Cause Effect
ORDER = ["who", "what", "where", "why", "how", "cause", "effect"]


def alignment(score: float, v: MoralVectorDef) -> str:
    if abs(score - 1.0) < 0.001:
        return v.virtue
    return f"{'Excess' if score > 1.0 else 'Deficit'}: {v.sin}"


@dataclass
class Concept:
    word: str
    scores: Dict[str, float]                  # depth-1, keyed by ORDER
    notes: Dict[str, str] = field(default_factory=dict)

    def vector(self) -> np.ndarray:
        return np.array([self.scores[k] for k in ORDER], dtype=float)

    # --- depth 1 ---
    def r_net(self) -> float:
        return FieldMath.fractal_ratio(self.vector().tolist())

    def as_idea(self) -> Idea:
        return Idea.of(**{k: (self.word, self.scores[k]) for k in ORDER})

    def depth1_report(self) -> str:
        lines = [f"  DEPTH 1 -- the seven plane scores ({self.word})"]
        for i, k in enumerate(ORDER):
            v, s = VECTORS[i], self.scores[k]
            note = self.notes.get(k, "")
            lines.append(f"    {v.interrogative:<7}{s:5.2f}  "
                         f"{alignment(s, v):<26}{note}")
        lines.append(f"    R_net {self.r_net():.4f}   "
                     f"{Judgement.evaluate(self.as_idea())}")
        return "\n".join(lines)

    # --- depth 2: generated, not authored ---
    def depth2(self) -> np.ndarray:
        """Outer product with itself: cell(a,b) = v_a * v_b. 49 cells."""
        v = self.vector()
        return np.outer(v, v).reshape(-1)

    def depth2_cell(self, a: int, b: int) -> Tuple[str, str, float]:
        v = self.vector()
        addr = f"Q{a + 1}.q{b + 1}"
        name = f"the {PLANE_NAMES[b]} of the {PLANE_NAMES[a]}"
        return addr, name, float(v[a] * v[b])

    def depth2_report(self, top: int = 8) -> str:
        cells = [self.depth2_cell(a, b) for a in range(7) for b in range(7)]
        lines = [f"  DEPTH 2 -- 49 generated cells, read as 'the b of the a'"]
        ranked = sorted(cells, key=lambda c: -abs(c[2] - 1.0))
        lines.append(f"    most deviant {top} (where the concept is most strained):")
        for addr, name, val in ranked[:top]:
            a = int(addr[1]) - 1
            lines.append(f"      {addr:<8}{val:6.3f}  {name:<34}"
                         f"{alignment(val, VECTORS[a])}")
        lines.append(f"    nearest Unity {top} (where it is virtuous):")
        for addr, name, val in ranked[-top:]:
            a = int(addr[1]) - 1
            lines.append(f"      {addr:<8}{val:6.3f}  {name:<34}"
                         f"{alignment(val, VECTORS[a])}")
        return "\n".join(lines)

    # --- depth 3 ---
    def depth3_branch(self, a: int, b: int) -> str:
        v = self.vector()
        lines = [f"  DEPTH 3 -- drilling Q{a+1}.q{b+1} "
                 f"({PLANE_NAMES[b]} of {PLANE_NAMES[a]})"]
        for c in range(7):
            val = float(v[a] * v[b] * v[c])
            addr = f"Q{a+1}.q{b+1}.q{c+1}"
            name = (f"the {PLANE_NAMES[c]} of the {PLANE_NAMES[b]} "
                    f"of the {PLANE_NAMES[a]}")
            lines.append(f"      {addr:<12}{val:6.3f}  {name}")
        return "\n".join(lines)

    def coherence_by_depth(self, max_depth: int = 4) -> str:
        P = float(np.prod(self.vector()))
        lines = ["  COHERENCE COMPOUNDS WITH DEPTH  (R_net = 1/product)"]
        lines.append(f"    depth 1: product {P:.4f}   R_net {1/P:.4f}")
        for d in range(2, max_depth + 1):
            # each depth-1 score appears 7^(d-1) * d times across 7^d cells
            exp = d * (7 ** (d - 1))
            prod = P ** exp
            rnet = math.inf if prod == 0 else 1.0 / prod
            lines.append(f"    depth {d}: product P^{exp:<5} "
                         f"R_net {rnet:.4g}")
        lines.append("    -> drilling an incoherent state does not waste effort,")
        lines.append("       it explodes. This is why the staircase gate exists.")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# THE HOUSE
#
# Scored against the real poles. Each line is a claim about houses that can be
# argued with, which is the point: the axes are named, so the model is
# contestable rather than opaque.
# ---------------------------------------------------------------------------

HOUSE = Concept(
    word="house",
    scores={
        "who":    0.55,   # a house is possessed, it does not possess
        "what":   1.25,   # held in stewardship, but the primary vehicle of hoarding
        "where":  1.00,   # the physical virtue realised: shelter beyond survival
        "why":    0.95,   # means close to what it is; little delusion
        "how":    1.05,   # built by craft, slightly over-ordered by code and convention
        "cause":  1.00,   # accumulates and holds its own history
        "effect": 0.95,   # generates unity, mildly short of it
    },
    notes={
        "who":    "no will of its own; confers sovereignty on the dweller",
        "what":   "the asset reading: housing as store of value",
        "where":  "this is the plane a house is FOR",
        "how":    "regulation and habit exceed what the craft requires",
    },
)

HOME = Concept(
    word="home",
    scores={
        "who":    0.90,   # nearly sovereign: it is where the dweller IS the will
        "what":   1.00,   # held, not hoarded
        "where":  1.00,
        "why":    1.05,   # carries more meaning than it strictly has
        "how":    0.95,
        "cause":  1.05,   # holds history heavily, sometimes revises it
        "effect": 1.00,   # Love/Unity realised
    },
    notes={
        "who":    "the difference from 'house' lives almost entirely here",
        "effect": "this is the plane a home is FOR",
    },
)


def compare(a: Concept, b: Concept) -> str:
    va, vb = a.vector(), b.vector()
    lines = [f"  {a.word.upper()} vs {b.word.upper()}"]
    for i, k in enumerate(ORDER):
        d = vb[i] - va[i]
        mark = "  <-- the difference" if abs(d) > 0.25 else ""
        lines.append(f"    {VECTORS[i].interrogative:<7}"
                     f"{va[i]:5.2f} -> {vb[i]:5.2f}  ({d:+.2f}){mark}")
    lines.append(f"    R_net {a.r_net():.4f} -> {b.r_net():.4f}")
    lines.append(f"    distance {float(np.linalg.norm(vb - va)):.4f}")
    return "\n".join(lines)


def main() -> None:
    B = generator()
    print("=" * 72)
    print("MODELLING A HOUSE IN THE FRACTAL QQCI FORMER")
    print("=" * 72)
    print()
    print(HOUSE.depth1_report())
    print()
    print(HOUSE.depth2_report())
    print()
    # Drill the two most interesting branches: the What (asset) and the Where.
    print(HOUSE.depth3_branch(1, 0))   # Q2.q1: the Who of the What -> whose asset
    print()
    print(HOUSE.depth3_branch(2, 6))   # Q3.q7: the Effect of the Where
    print()
    print(HOUSE.coherence_by_depth())
    print()
    print("=" * 72)
    print(compare(HOUSE, HOME))
    print()
    print("  The vector difference is concentrated on Q1. A home is a house")
    print("  whose Who has been raised. Nothing else moves much, and the")
    print("  geometry says so without being told.")
    print("=" * 72)


if __name__ == "__main__":
    main()
