"""
Qqci core engine: the 7-plane skeleton as executable geometry.

Python port of RealityClassification.v2.cs, kept deliberately faithful:
- Plane enum is the fixed metaclass, never revised at runtime.
- QqciAddress is class identity; the ordered interrogative path IS the identity.
- TruthState is the carved hole / document template.
- Meaning is the QANode instance.

New here (not in the C# version): the contextual min-max gate, SignedSpan,
and per-plane parallax intersection scoring.

No training. No learned weights. Everything is structure.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import math
from dataclasses import dataclass, field
from enum import Enum, IntEnum
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


# ---------------------------------------------------------------------------
# THE METACLASS: the fixed 7-plane skeleton.
# ---------------------------------------------------------------------------

class Plane(IntEnum):
    WHO = 1     # Metaphysical - Will and Direction (the driver axis)
    WHAT = 2    # Possible     - Faith and Probability   (+x)
    WHERE = 3   # Physical     - Matter and Distance     (-x)
    WHY = 4     # Lyrical      - Meaning and Resonance   (+y)
    HOW = 5     # Logical      - Count and Consistency   (-y)
    CAUSE = 6   # Historical   - Sequence and Causality  (+z)
    EFFECT = 7  # Emotive      - Passion and Consequence (-z)


PLANE_NAMES = {
    Plane.WHO: "Who/Metaphysical",
    Plane.WHAT: "What/Possible",
    Plane.WHERE: "Where/Physical",
    Plane.WHY: "Why/Lyrical",
    Plane.HOW: "How/Logical",
    Plane.CAUSE: "Cause/Historical",
    Plane.EFFECT: "Effect/Emotive",
}

# The 42-Structure axis pairings. Q1 is the unpaired driver.
AXIS_PAIRS = {
    "body_lateral": (Plane.WHAT, Plane.WHERE),        # +x / -x
    "mind_longitudinal": (Plane.WHY, Plane.HOW),      # +y / -y
    "soul_vertical": (Plane.CAUSE, Plane.EFFECT),     # +z / -z
}


class ModalPosition(Enum):
    """The Universal Relativity Frame: five positions plus the gap."""
    ARE = "are"                # center: present assertion, the anchor
    CAN_BE = "can_be"          # top-left: open possibility
    NOT_ALL = "not_all"        # top-right: bounded negation
    NOT_REALLY = "not_really"  # bottom-left: soft negation
    WAS_LIKE = "was_like"      # bottom-right: analogical past
    IN_GAP = "in_gap"          # between positions: triggers sub-frame drill


class SemanticRelation(Enum):
    """Kept from {Meaning}.cs. Derived from plane geometry, not authored."""
    SIMILAR = "similar"
    EQUIVALENT = "equivalent"
    DERIVATIVE = "derivative"
    OPPOSITE = "opposite"
    NONE = "none"


class BeliefState(Enum):
    """
    Actualism: the personal belief state held per active plane.
    Meaning is generated by how these MOVE across planes under constraint,
    not by their static assignment.
    """
    TRUTH = "="            # accepted, enforced, or stabilised reality
    WILL_TO_KNOW = "+?"    # inquiry, exploration, testing
    LIE = "<"              # distortion, manipulation, concealment
    INDIFFERENT = "~?"     # neglect, neutrality, entropy
    INSULT = ">"           # attack, domination, destabilisation
    WILL_NOT_TO_KNOW = "-?"  # denial, repression, taboo


class Systemic(Enum):
    """Order vs chaos per plane-state pairing. They can coexist across planes."""
    ORDER = "order"    # stabilises, constrains, aligns agents
    CHAOS = "chaos"    # destabilises, propagates uncertainty, multiplies outcomes
    NEUTRAL = "neutral"


class FunctionalIdentity(Enum):
    """The agent's functional role, not its literal one."""
    STABILISER = "stabiliser_of_truth"
    INQUIRER = "driver_of_inquiry"
    SUPPRESSOR = "suppressor_of_knowledge"
    ENFORCER = "enforcer_of_constraint"
    CATALYST = "catalyst_of_collapse"
    UNSET = "unset"


# Which belief states read as order and which as chaos, by default.
# Social interpretation may invert these (Actualism step 3), so this is a
# default reading and not a fixed law.
DEFAULT_SYSTEMIC = {
    BeliefState.TRUTH: Systemic.ORDER,
    BeliefState.WILL_TO_KNOW: Systemic.CHAOS,      # inquiry destabilises
    BeliefState.LIE: Systemic.CHAOS,
    BeliefState.INDIFFERENT: Systemic.NEUTRAL,
    BeliefState.INSULT: Systemic.CHAOS,
    BeliefState.WILL_NOT_TO_KNOW: Systemic.ORDER,  # repression stabilises, cheaply
}


class TensorRank(IntEnum):
    CHARACTER = 0  # the alphabet: irreducible basis, the TBE floor
    WORD = 1
    PHRASE = 2     # SAEL transitions live here
    MEANING = 3


class FillState(Enum):
    CARVED = "carved"            # hole exists, nothing accreted
    ACCRETING = "accreting"
    FILLED = "filled"            # === reached
    FUNDAMENTAL = "fundamental"  # TBE: hit irreducible units
    FALSE_FILL = "false_fill"    # cross-plane disagreement at apparent fill
    NEVER_FILLED = "never_filled"


# ---------------------------------------------------------------------------
# THE ADDRESS: the interrogative path IS the identity.
# Compositional, ordered, non-commutative. Q4.q5 != Q5.q4.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class QqciAddress:
    path: Tuple[Plane, ...]
    language: int = 0  # 0 = language-agnostic convergence root

    def __post_init__(self):
        if not self.path:
            raise ValueError("An address requires at least one plane.")

    @staticmethod
    def of(*planes: Plane, language: int = 0) -> "QqciAddress":
        return QqciAddress(tuple(planes), language)

    def drill(self, nxt: Plane) -> "QqciAddress":
        """The +i operator: descend one interrogative deeper."""
        return QqciAddress(self.path + (nxt,), self.language)

    def ascend(self) -> "QqciAddress":
        """Up-channel move. Root addresses return themselves."""
        if len(self.path) > 1:
            return QqciAddress(self.path[:-1], self.language)
        return self

    def in_language(self, language: int) -> "QqciAddress":
        return QqciAddress(self.path, language)

    @property
    def depth(self) -> int:
        return len(self.path)

    @property
    def root(self) -> Plane:
        """The domain being operated over."""
        return self.path[0]

    @property
    def leaf(self) -> Plane:
        """The operating interrogative."""
        return self.path[-1]

    @property
    def canonical(self) -> str:
        head = f"Q{int(self.path[0])}"
        tail = "".join(f".q{int(p)}" for p in self.path[1:])
        return f"L{self.language}:{head}{tail}"

    def __str__(self) -> str:
        return self.canonical


def axomic_id(address: QqciAddress, payload: str) -> str:
    """
    Deterministic content-addressed identity. Same address + payload = same ID,
    always. This is what makes Query IS the Write idempotent. No randomness.
    """
    h = hashlib.sha256(f"{address.canonical}|{payload}".encode("utf-8"))
    return h.hexdigest()[:16]


# ---------------------------------------------------------------------------
# SIGNED SPAN: every concept carries its own contextual range.
# love = (-love, ~love, +love) with magnitude.
# Antonyms are poles of one axis, not separate points.
# ---------------------------------------------------------------------------

@dataclass
class SignedSpan:
    negative_pole: str
    positive_pole: str
    position: float = 0.0   # -1.0 .. +1.0, where the claim sits on the axis
    magnitude: float = 0.0  # intensity, 0.0 .. 1.0

    def read(self) -> str:
        if self.position < -0.33:
            return self.negative_pole
        if self.position > 0.33:
            return self.positive_pole
        return f"~{self.positive_pole}"

    def signed_value(self) -> float:
        return self.position * self.magnitude


# ---------------------------------------------------------------------------
# COHERENCE: a 7-vector, never a scalar.
# A scalar cannot disagree with itself, so a scalar cannot detect false fill.
# ---------------------------------------------------------------------------

@dataclass
class CoherenceVector:
    scores: Dict[Plane, float] = field(default_factory=dict)

    def __post_init__(self):
        for p in Plane:
            self.scores.setdefault(p, 0.0)

    def __getitem__(self, p: Plane) -> float:
        return self.scores[p]

    def __setitem__(self, p: Plane, v: float) -> None:
        self.scores[p] = v

    @property
    def net(self) -> float:
        return sum(self.scores.values()) / len(self.scores)

    @property
    def active(self) -> Dict[Plane, float]:
        return {p: v for p, v in self.scores.items() if v > 0.0}

    @property
    def disagreement(self) -> float:
        """
        Max pairwise divergence across ACTIVE planes. Planes that cast no ray
        are silent, not dissenting: an unengaged plane must not be read as
        disagreement, or every sparse observation would look like false fill.
        """
        act = list(self.active.values())
        if len(act) < 2:
            return 0.0
        return max(act) - min(act)

    def mix_weights(self) -> Dict[Plane, float]:
        """Interpretable mixing: '40% Q4, 30% Q6, 30% Q1'."""
        total = sum(self.scores.values())
        if total <= 0:
            return {p: 0.0 for p in Plane}
        return {p: v / total for p, v in self.scores.items()}

    def readout(self, threshold: float = 0.01) -> str:
        w = self.mix_weights()
        parts = [
            f"{int(round(v * 100))}% {PLANE_NAMES[p].split('/')[0]}"
            for p, v in sorted(w.items(), key=lambda kv: -kv[1])
            if v > threshold
        ]
        return ", ".join(parts) if parts else "(empty)"


# ---------------------------------------------------------------------------
# THE CONTEXTUAL MIN-MAX GATE (replaces GELU)
#
# GELU gates on absolute magnitude with a shape identical everywhere.
# This gates on relative position within the pool's own observed range, so:
#   - it is smooth while the pool is disordered (wide range, mushy positions)
#   - it sharpens toward a hard staircase gate as the pool orders
#   - fill is detectable as range convergence, not a magic constant
#   - candidates that land between resolvable positions are IN_GAP: drill
# ---------------------------------------------------------------------------

@dataclass
class ContextualRange:
    lo: float = 0.0
    hi: float = 0.0
    n: int = 0
    _prev_width: float = -1.0
    _stable_ticks: int = 0

    def expand(self, values: Iterable[float]) -> None:
        vals = list(values)
        if not vals:
            return
        if self.n == 0:
            self.lo, self.hi = min(vals), max(vals)
        else:
            self.lo = min(self.lo, min(vals))
            self.hi = max(self.hi, max(vals))
        self.n += len(vals)

    @property
    def width(self) -> float:
        return self.hi - self.lo

    def tick(self, tol: float = 1e-6) -> None:
        """Record whether the range moved this pass. Stability implies fill."""
        if self._prev_width >= 0 and abs(self.width - self._prev_width) <= tol:
            self._stable_ticks += 1
        else:
            self._stable_ticks = 0
        self._prev_width = self.width

    @property
    def converged(self) -> bool:
        return self._stable_ticks >= 1

    def position_of(self, value: float) -> float:
        """Normalised position in range: 0.0 at min, 1.0 at max. Dimensionless."""
        if self.width <= 1e-12:
            return 1.0 if self.n else 0.0
        return (value - self.lo) / self.width


def gate(value: float, rng: ContextualRange, sharpness: float,
         gap_band: Tuple[float, float] = (0.40, 0.60)) -> Tuple[float, ModalPosition]:
    """
    Returns (gated_value, modal_position).

    sharpness in [0,1]: 0 = fully soft (early accretion, gradients flow),
    1 = hard staircase gate (pool ordered, below-threshold contributes zero).
    The hard gate is the LIMIT of the soft gate, not an imposed alternative.
    """
    pos = rng.position_of(value)

    # Soft: pass through relative position. Hard: binary threshold at midpoint.
    soft = pos
    hard = 1.0 if pos >= 0.5 else 0.0
    gated = (1.0 - sharpness) * soft + sharpness * hard

    if gap_band[0] <= pos <= gap_band[1] and sharpness < 0.75:
        modal = ModalPosition.IN_GAP     # ambiguity descends, never snaps
    elif pos >= 0.85:
        modal = ModalPosition.ARE
    elif pos >= 0.5:
        modal = ModalPosition.CAN_BE
    elif pos >= 0.15:
        modal = ModalPosition.NOT_REALLY
    else:
        modal = ModalPosition.NOT_ALL

    return gated, modal


# ---------------------------------------------------------------------------
# MEANING: a QANode instance. Identity derives from composition.
# ---------------------------------------------------------------------------

@dataclass
class Meaning:
    """
    Faithful port of Meaning from {Meaning}.cs, with three substitutions and
    one addition, each noted:

      Polarity   -> modal (ModalPosition) + spans. A four-value polarity enum
                    cannot express a position on an axis; the signed span can,
                    and subsumes it.
      TruthScore -> coherence (CoherenceVector). A scalar cannot disagree with
                    itself, so a scalar cannot detect false fill.
      6 scale    -> address (QqciAddress). The interrogative path IS the
        layers      identity; scale layers are the address book, not the space.
      spans      -> NEW. The word's position on each of the 7 plane axes.
                    This is where the meaning actually lives.

    Kept from the original: Word, DefinitiveMeaning, Pronunciation,
    SubMeanings, Related, and the AxomicID (now deterministic, not random).
    """
    word: str
    address: QqciAddress
    rank: TensorRank = TensorRank.MEANING
    definitive: Optional[str] = None
    pronunciation: Optional[str] = None
    components: Tuple[str, ...] = ()          # axomic IDs at rank - 1
    sub_meanings: List["Meaning"] = field(default_factory=list)
    related: List[Tuple[str, "SemanticRelation"]] = field(default_factory=list)
    # The 7D position: one TruthScore per plane, centred on Unity.
    # 1.0 = virtue realised, >1.0 = Excess of the sin, <1.0 = Deficit of it.
    # This is the project's own geometry (MoralVectorDef / MoralScore) and it
    # replaces the bipolar `spans` experiment, which could not express
    # "too much and too little are the same failure".
    plane_scores: Dict[Plane, float] = field(default_factory=dict)
    spans: Dict[Plane, SignedSpan] = field(default_factory=dict)  # deprecated
    coherence: CoherenceVector = field(default_factory=CoherenceVector)
    modal: ModalPosition = ModalPosition.ARE
    payload: Optional[dict] = None            # rank-2 carries its SAEL tuple
    carved_at: int = 0                        # temporal layer: day of year

    def __post_init__(self):
        if self.definitive is None:
            self.definitive = self.word
        if self.carved_at == 0:
            self.carved_at = _dt.datetime.utcnow().timetuple().tm_yday

    @property
    def axomic_id(self) -> str:
        # Compositional identity: a word IS its letters, a phrase IS its words.
        payload = ",".join(self.components) if self.components else self.word
        return axomic_id(self.address, payload)

    def add_related(self, other: "Meaning", relation: "SemanticRelation") -> None:
        self.related.append((other.word, relation))

    # --- the 7D position: this IS the definition ---

    def signed(self, p: Plane) -> Optional[float]:
        s = self.spans.get(p)
        return None if s is None else s.signed_value()

    def vector(self) -> List[Optional[float]]:
        """Signed value per plane, None where the plane is inactive."""
        return [self.signed(p) for p in Plane]

    def derived_address(self, language: int = 0) -> QqciAddress:
        """
        The address falls out of the content: the two strongest planes in
        strength order. Derived, never assigned alongside the content.
        """
        ranked = sorted(
            ((p, abs(v)) for p in Plane if (v := self.signed(p)) is not None),
            key=lambda kv: (-kv[1], kv[0]))
        if len(ranked) >= 2:
            return QqciAddress.of(ranked[0][0], ranked[1][0], language=language)
        if ranked:
            return QqciAddress.of(ranked[0][0], language=language)
        return QqciAddress.of(Plane.WHAT, language=language)

    def readout(self) -> str:
        return " ".join(
            f"{p.name}:-" if (v := self.signed(p)) is None else f"{p.name}:{v:+.2f}"
            for p in Plane)


def FieldMath_fractal_ratio(scores: Sequence[float]) -> float:
    """
    R_net = 1 / product(scores). Duplicated from vft.FieldMath.fractal_ratio
    so the engine has no import cycle with vft.py; the two must stay identical.
    Returns infinity when any score is zero: one collapsed plane collapses the
    whole state, which is the property a mean cannot express.
    """
    product = 1.0
    for s in scores:
        product *= s
    if product == 0:
        return math.inf
    return 1.0 / product


def plane_distance(a: Meaning, b: Meaning) -> float:
    """
    Distance over shared active planes. A plane active in one and absent in
    the other takes a fixed penalty rather than being skipped: differing in
    WHICH planes are active is itself a difference, and absence is meaningful.
    """
    shared = [p for p in Plane if p in a.spans and p in b.spans]
    only = [p for p in Plane if (p in a.spans) != (p in b.spans)]
    total = sum((a.signed(p) - b.signed(p)) ** 2 for p in shared)
    total += 1.0 * len(only)
    denom = len(shared) + len(only)
    return math.sqrt(total / denom) if denom else 1.0


class MeaningRegistry:
    """
    Flat, content-addressed, O(1). Query IS the Write: carving an address that
    exists returns it (recall as residual warp); carving one that does not
    creates and persists it.

    Includes the reverse component index that the C# version still owes.
    """

    def __init__(self, meta: Optional["MeaningMetaRegistry"] = None) -> None:
        self._by_id: Dict[str, Meaning] = {}
        self._by_word: Dict[str, List[str]] = {}
        self._by_component: Dict[str, List[str]] = {}  # component -> containers
        # Every carve files itself in the address book too. Content and
        # location are separate concerns kept deliberately in sync.
        self.meta = meta if meta is not None else MeaningMetaRegistry()

    def carve_or_recall(self, word: str, address: QqciAddress,
                        rank: TensorRank = TensorRank.MEANING,
                        components: Sequence[str] = (),
                        definitive: Optional[str] = None,
                        payload: Optional[dict] = None) -> Meaning:
        probe = Meaning(word=word, address=address, rank=rank,
                        components=tuple(components), definitive=definitive,
                        payload=payload)
        mid = probe.axomic_id
        existing = self._by_id.get(mid)
        if existing is not None:
            return existing

        self._by_id[mid] = probe
        self._by_word.setdefault(word, []).append(mid)
        for c in probe.components:
            self._by_component.setdefault(c, []).append(mid)
        self.meta.add_meaning(probe)
        return probe

    def refile(self, m: Meaning) -> None:
        """
        Re-index a node whose content changed after carving (spans assigned,
        definitive updated). The address book must not go stale.
        """
        self.meta.add_meaning(m)

    def get(self, axid: str) -> Optional[Meaning]:
        return self._by_id.get(axid)

    def by_word(self, word: str) -> List[Meaning]:
        return [self._by_id[i] for i in self._by_word.get(word, [])]

    def containers_of(self, axid: str) -> List[Meaning]:
        """Reverse index: which higher-rank compositions contain this node."""
        return [self._by_id[i] for i in self._by_component.get(axid, [])]

    def contract(self, raw: str, address: QqciAddress) -> Meaning:
        """
        The contraction ladder: alphabet-TS matches word-TS matches meaning-TS.
        Decompose to rank-0 basis vectors, compose upward to a rank-1 identity,
        then index rank-2+ compositions via the reverse index (O(1), not a scan).
        """
        char_addr = QqciAddress.of(address.root, language=address.language)
        char_ids = [
            self.carve_or_recall(ch, char_addr, rank=TensorRank.CHARACTER).axomic_id
            for ch in raw
        ]
        word_ts = self.carve_or_recall(raw, address, rank=TensorRank.WORD,
                                       components=char_ids)
        for container in self.containers_of(word_ts.axomic_id):
            if container.rank >= TensorRank.PHRASE:
                return container
        return word_ts  # no higher fill yet: word-TS is the deepest resolved rank

    def seed_alphabet(self, letters: str, language: int = 0) -> List[Meaning]:
        """
        Rank-0 seed: the enumerable TBE floor. After this, 'fundamentals are hit'
        is a membership test rather than a philosophical claim.
        """
        addr = QqciAddress.of(Plane.WHERE, language=language)
        return [self.carve_or_recall(c, addr, rank=TensorRank.CHARACTER)
                for c in letters]

    def is_fundamental(self, m: Meaning) -> bool:
        return m.rank == TensorRank.CHARACTER

    @property
    def size(self) -> int:
        return len(self._by_id)


# ---------------------------------------------------------------------------
# TRUTHSTATE: the carved hole, the document template, the bounded pool.
# ---------------------------------------------------------------------------

class MeaningMetaRegistry:
    """
    The ADDRESS BOOK. Port of MeaningMetaRegistry from {Meaning}.cs.

    This is a separate concern from MeaningRegistry and both must exist:
      MeaningRegistry     content-addressed. Answers "what does this mean?"
                          Identity is the plane vector and the interrogative
                          path. This is the semantic space.
      MeaningMetaRegistry scale-indexed. Answers "where does this node sit?"
                          Language, rank, temporal, word. This is the filing
                          system, and it carries no meaning at all: it is
                          never indexed by plane, since plane is a system-A
                          (Qqci form) coordinate, not a filing key.

    Collapsing the two was a mistake: it made the scale layers look like
    semantic dimensions, which is the category error that produced the
    six-nested-dictionaries design in the first place.

    The original nested the six layers, so a lookup was six dereferences and a
    miss anywhere returned null. This uses parallel inverted indices instead,
    so any SUBSET of coordinates can be queried (the original required all six
    or none) and every lookup is O(1) per index plus a set intersection.
    """

    def __init__(self) -> None:
        self._by_axomic: Dict[str, Meaning] = {}
        self._by_language: Dict[int, set] = {}
        self._by_rank: Dict[TensorRank, set] = {}
        self._by_temporal: Dict[int, set] = {}
        self._by_word: Dict[str, set] = {}
        self._by_definitive: Dict[str, set] = {}

    # --- AddMeaning, but the coordinates are read off the node ---
    def add_meaning(self, m: Meaning) -> str:
        axid = m.axomic_id
        self._by_axomic[axid] = m
        self._by_language.setdefault(m.address.language, set()).add(axid)
        self._by_rank.setdefault(m.rank, set()).add(axid)
        self._by_temporal.setdefault(m.carved_at, set()).add(axid)
        self._by_word.setdefault(m.word, set()).add(axid)
        self._by_definitive.setdefault(m.definitive or m.word, set()).add(axid)
        return axid

    # --- GetMeaning, but any subset of coordinates is a legal query ---
    # No root_plane parameter: plane is a system-A (Qqci form) coordinate,
    # not a filing key. Querying by plane belongs to MeaningRegistry /
    # CoherenceVector, never to this filing index.
    def get_meaning(self, *, axomic_id: Optional[str] = None,
                    language: Optional[int] = None,
                    rank: Optional[TensorRank] = None,
                    temporal: Optional[int] = None,
                    word: Optional[str] = None,
                    definitive: Optional[str] = None) -> List[Meaning]:
        if axomic_id is not None:
            m = self._by_axomic.get(axomic_id)
            return [m] if m else []

        sets = []
        if language is not None:
            sets.append(self._by_language.get(language, set()))
        if rank is not None:
            sets.append(self._by_rank.get(rank, set()))
        if temporal is not None:
            sets.append(self._by_temporal.get(temporal, set()))
        if word is not None:
            sets.append(self._by_word.get(word, set()))
        if definitive is not None:
            sets.append(self._by_definitive.get(definitive, set()))

        if not sets:
            return list(self._by_axomic.values())
        hits = set.intersection(*sets) if len(sets) > 1 else sets[0]
        return [self._by_axomic[a] for a in sorted(hits)]

    # --- the two convenience lookups the original had ---
    def get_by_word(self, word: str) -> List[Meaning]:
        return self.get_meaning(word=word)

    def get_by_meaning(self, definitive: str) -> List[Meaning]:
        """
        The original scanned all six nested levels to find one match and
        returned the first. This is an index hit and returns ALL matches,
        because several words legitimately share a definitive meaning: that
        is what an equivalence class IS, and returning only the first
        discards the collapse.
        """
        return self.get_meaning(definitive=definitive)

    # --- what the flat original could not answer at all ---
    def plane_census(self) -> Dict[Plane, int]:
        """
        How many stored nodes are rooted at each plane. A read-only report
        over each node's own system-A address, computed on demand rather
        than maintained as a filing index: the meta-registry does not
        organise storage by plane, it only reports on what is stored.
        """
        counts: Dict[Plane, int] = {p: 0 for p in Plane}
        for m in self._by_axomic.values():
            counts[m.address.root] += 1
        return counts

    def rank_census(self) -> Dict[TensorRank, int]:
        return {r: len(self._by_rank.get(r, set())) for r in TensorRank}

    @property
    def size(self) -> int:
        return len(self._by_axomic)


@dataclass
class TruthState:
    address: QqciAddress
    budget: int = 7
    tolerance: float = 0.15
    state: FillState = FillState.CARVED
    pool: List[Meaning] = field(default_factory=list)
    slots: Dict[Plane, Meaning] = field(default_factory=dict)
    parent: Optional["TruthState"] = None
    children: List["TruthState"] = field(default_factory=list)
    rng: ContextualRange = field(default_factory=ContextualRange)
    coherence: CoherenceVector = field(default_factory=CoherenceVector)
    engagement: CoherenceVector = field(default_factory=CoherenceVector)

    # --- Excavation: the hole pulls material in. ---
    def accrete(self, m: Meaning, engagement: float = 1.0,
                assertion: float = 1.0) -> None:
        """
        ENGAGEMENT is how strongly this plane is involved (the action's plane
        signature). ASSERTION is what the plane says about the claim.

        These are different quantities and conflating them was a real bug: a
        plane weakly engaged is SILENT, not DISSENTING. Only assertions can
        disagree, so only assertions feed the false-fill detector. Engagement
        feeds the interpretable mix readout.
        """
        if self.state == FillState.FUNDAMENTAL:
            return  # TBE is terminal: irreducible units admit nothing further
        if self.state == FillState.FILLED:
            # A fill is PROVISIONAL, not sealed. Late dissent must be able to
            # reopen it, or false fill becomes undetectable the moment it is
            # marked resolved, which is the failure mode this whole mechanism
            # exists to catch. Agreeable material adds nothing to a filled
            # hole; dissenting material reopens it.
            p_existing = self.coherence[m.address.root]
            if p_existing != 0.0 and assertion >= p_existing:
                return
        self.state = FillState.ACCRETING
        self.pool.append(m)
        self.rng.expand([engagement])
        # Material settles into the sub-basin of its root plane.
        self.slots.setdefault(m.address.root, m)
        p = m.address.root
        self.engagement[p] = max(self.engagement[p], engagement)
        # Multiple observers of one plane: keep the WEAKEST assertion, so a
        # single dissenting vantage is not averaged away by agreeable ones.
        prev = self.coherence[p]
        self.coherence[p] = assertion if prev == 0.0 else min(prev, assertion)

    @property
    def sharpness(self) -> float:
        """Anneals with pool order: soft while accreting, hard as it converges."""
        if self.rng.converged:
            return 1.0
        return min(1.0, len(self.pool) / 8.0)

    def evaluate_fill(self) -> FillState:
        """
        The Coherence Gate Axiom, vectorised:
        [Q|A / A|Q] === { Y=1 ; N != 1 ; Insult > 1 }
        with cross-plane disagreement as the false-fill detector.
        """
        self.rng.tick()
        active = self.coherence.active
        if not active:
            self.state = FillState.ACCRETING
            return self.state

        eps = 1e-9  # float guard: 1.00 - 0.70 is not exactly 0.30
        # The Fractal Ratio Protocol: R_net = 1 / product(scores).
        # NOT a mean. A mean cannot diverge; the fractal ratio goes to infinity
        # when any single plane collapses to zero, which is exactly the failure
        # this gate exists to catch. Using the mean here was a real bug.
        net = FieldMath_fractal_ratio(list(active.values()))
        in_band = (1.0 - self.tolerance - eps) <= net <= (1.0 + self.tolerance + eps)
        agree = self.coherence.disagreement <= self.tolerance * 2 + eps

        if in_band and agree and self.rng.converged:
            self.state = FillState.FILLED          # === : Y = 1 (TRUTH)
        elif in_band and not agree:
            self.state = FillState.FALSE_FILL      # planes disagree: stealth
        elif net > 1.0 + self.tolerance:
            self.state = FillState.FALSE_FILL      # Insult > 1 (CHAOS)
        else:
            self.state = FillState.ACCRETING       # N != 1, keep pulling
        return self.state

    # --- Staircase gate: a step must fill before it overflows. ---
    def drill_into(self, nxt: Plane) -> Optional["TruthState"]:
        if self.state != FillState.FILLED:
            raise RuntimeError(
                f"Staircase gating violated: step must fill before it overflows "
                f"(state={self.state.value}, address={self.address})"
            )
        if self.address.depth >= self.budget:
            self.state = FillState.FUNDAMENTAL  # TBE by budget exhaustion
            return None
        child = TruthState(address=self.address.drill(nxt),
                           budget=self.budget, tolerance=self.tolerance,
                           parent=self)
        # The child's addressable universe IS the parent's accreted pool.
        self.children.append(child)
        return child

    # --- Up-channel: never-fills and false-fills escalate and widen. ---
    def escalate(self) -> Optional["TruthState"]:
        if self.parent is None:
            self.state = FillState.NEVER_FILLED
            return None
        self.parent.state = FillState.ACCRETING  # reopen and widen the parent hole
        return self.parent


# ---------------------------------------------------------------------------
# PARALLAX: detection as intersection of independent projections.
#
# Pixel-motion-voxel-projection, mapped. Each observer (plane / language /
# model) casts a constraint ray rather than a verdict. Material earns its place
# only where rays from independent vantages intersect. One-ray content is
# stealth: plausible from a single vantage, unsupported from any other.
# ---------------------------------------------------------------------------

@dataclass
class Ray:
    observer: str          # which vantage cast it
    plane: Plane           # which camera position
    target: str            # the voxel: a canonical coordinate string
    strength: float = 1.0


def intersect(rays: Sequence[Ray], min_observers: int = 2
              ) -> List[Tuple[str, int, float, List[Plane]]]:
    """
    Returns [(target, distinct_observer_count, summed_strength, planes)]
    sorted by observer count then strength. Noise casts rays too, but random
    rays are statistically incapable of co-intersecting from independent
    vantages, so noise self-filters without a denoising step.
    """
    buckets: Dict[str, List[Ray]] = {}
    for r in rays:
        buckets.setdefault(r.target, []).append(r)

    out = []
    for target, rs in buckets.items():
        observers = {r.observer for r in rs}
        if len(observers) < min_observers:
            continue
        planes = sorted({r.plane for r in rs})
        out.append((target, len(observers), sum(r.strength for r in rs), planes))

    out.sort(key=lambda t: (-t[1], -t[2]))
    return out


def depth_map(rays: Sequence[Ray]) -> Dict[str, float]:
    """
    Stereo bonus: displacement between vantage readings estimates depth.
    Low variance across observers = deep, load-bearing, near the basin floor.
    High variance = shallow, vantage-dependent, near the surface.
    """
    buckets: Dict[str, List[float]] = {}
    for r in rays:
        buckets.setdefault(r.target, []).append(r.strength)
    out = {}
    for target, vals in buckets.items():
        if len(vals) < 2:
            out[target] = 0.0
            continue
        mean = sum(vals) / len(vals)
        var = sum((v - mean) ** 2 for v in vals) / len(vals)
        out[target] = 1.0 / (1.0 + var)  # 1.0 = perfect agreement = deepest
    return out
