import os

file_path = "E:/Vector Field Theory/VFT Docs/_VFT MD/WWSUTRU/America/Trump_Manual_Score_Review.md"

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    (
        "#### 17: Who.What.How : The Boss\n*   **Current Score:** -1\n*   **Updated Score:** -1 (Active Opposition)\n*   **Current Trump υ / ψ:** -0.9 / +0.9\n*   **Updated Trump υ / ψ:** -0.9 / +0.9\n*   **Justification:** The American concept of \"The Boss\" combines authority with a fundamental responsibility for the enterprise and its workers. Trump operates purely on authority while completely severing the responsibility. He demands absolute, groveling loyalty but accepts zero blame for systemic failures, constantly firing subordinates to protect his own ego. He treats the Republic not as a sacred trust to be managed, but as a hostile leverage buyout to be liquidated for personal brand enhancement.",
        "#### 17: Who.What.How : The Boss\n*   **Current Score:** -1\n*   **Updated Score:** +1 (Corrected Error: Amplification)\n*   **Current Trump υ / ψ:** -0.9 / +0.9\n*   **Updated Trump υ / ψ:** -0.9 / +0.9\n*   **Justification:** **CRITICAL AI CORRECTION:** The original -1 score failed to recognize that 'The Boss' is a Kanonic archetype that Trump executes perfectly. He is the apotheosis of the American Boss—demanding absolute loyalty, ruling through personal fiat rather than institutional procedure, and equating his personal success entirely with the success of the enterprise. Rather than opposing the archetype, he amplifies its most pure, unconstrained, and dictatorial elements, bringing the ruthless logic of the private boardroom directly into the public square."
    ),
    (
        "#### 29: Who.Cause.Where : The Evangelist\n*   **Current Score:** -1\n*   **Updated Score:** -1 (Active Opposition)\n*   **Current Trump υ / ψ:** -1.0 / +0.9\n*   **Updated Trump υ / ψ:** -1.0 / +0.9\n*   **Justification:** The Evangelist seeks to convert the masses to a higher spiritual truth through impassioned persuasion. Trump utilizes the furious energy of the revival tent, but he strips it entirely of its spiritual or moral content. He is an evangelist of the Self, demanding absolute, uncritical faith from his followers not in a higher Kanonic ideal or a divine structure, but exclusively in his own personal infallibility. He corrupts the mechanism of mass spiritual awakening into a mechanism for mass political subjugation.",
        "#### 29: Who.Cause.Where : The Evangelist\n*   **Current Score:** -1\n*   **Updated Score:** +1 (Corrected Error: Amplification)\n*   **Current Trump υ / ψ:** -1.0 / +0.9\n*   **Updated Trump υ / ψ:** -1.0 / +0.9\n*   **Justification:** **CRITICAL AI CORRECTION:** While Trump is personally devoid of orthodox religious piety, he perfectly executes the *mechanics* of the American Evangelist. He is a master of the revival tent aesthetic, utilizing mass rallies to generate emotional catharsis, demanding absolute faith from his followers regardless of empirical truth, and selling a prosperity gospel of national greatness. He correctly identified that the political base desired a savior figure rather than a policy manager, and he flawlessly adopted the rhetorical cadence and charismatic authority of the tent preacher to deliver it."
    ),
    (
        "#### 149: Where.Effect.Where : The Action Movie\n*   **Current Score:** -1\n*   **Updated Score:** -1 (Active Opposition)\n*   **Current Trump υ / ψ:** -0.8 / +1.0\n*   **Updated Trump υ / ψ:** -0.8 / +1.0\n*   **Justification:** The Action Movie is the Kanonic simplification of geopolitical conflict into a binary, kinetic spectacle. Trump is obsessed with this aesthetic, constantly demanding military parades and utilizing the rhetoric of explosive, immediate violence (\"fire and fury\"). However, he treats complex strategic challenges as if they can be resolved in a 90-minute narrative arc through sheer bravado. By attempting to govern via theatrical trailer rather than strategic doctrine, he actively degrading the serious, slow, necessary work of actual statecraft.",
        "#### 149: Where.Effect.Where : The Action Movie\n*   **Current Score:** -1\n*   **Updated Score:** +1 (Corrected Error: Amplification)\n*   **Current Trump υ / ψ:** -0.8 / +1.0\n*   **Updated Trump υ / ψ:** -0.8 / +1.0\n*   **Justification:** **CRITICAL AI CORRECTION:** Trump perfectly intuitively grasps and executes the physics of the American Action Movie, where complex geopolitical problems are reduced to a simple binary of good versus evil, resolvable only through the sheer, unilateral use of force by an anti-hero. He treats the presidency as a sustained theatrical performance, demanding dramatic plot twists, easily identifiable villains, and explosive rhetoric. He successfully merged the entertainment logic of the blockbuster with the execution of state power, giving the base exactly the cinematic resolution they crave over complex reality."
    ),
    (
        "#### 151: Where.Effect.Effect : The Con Man\n*   **Current Score:** -1\n*   **Updated Score:** -1 (Active Opposition)\n*   **Current Trump υ / ψ:** -1.0 / +0.9\n*   **Updated Trump υ / ψ:** -1.0 / +0.9\n*   **Justification:** The Con Man (Confidence Man) thrives in the fluid, unregulated spaces of American capitalism by exploiting the inherent trust required for the system to function. Trump elevates the methodology of the hustle to the highest level of government. He operates almost entirely in the realm of generating false confidence, making massive promises he knows cannot be kept (e.g., \"Mexico will pay for the wall\"), and exploiting the faith of his base for political and financial extraction. He actively destroys the baseline of trust required between the sovereign and the citizenry.",
        "#### 151: Where.Effect.Effect : The Con Man\n*   **Current Score:** -1\n*   **Updated Score:** +1 (Corrected Error: Amplification)\n*   **Current Trump υ / ψ:** -1.0 / +0.9\n*   **Updated Trump υ / ψ:** -1.0 / +0.9\n*   **Justification:** **CRITICAL AI CORRECTION:** The original -1 score misses the point that 'The Con Man' (the Confidence Man) is a deeply embedded Kanonic archetype reflecting the dark side of American reinvention and salesmanship. Trump is the apex predator of this archetype. He operates almost entirely on the generation of false confidence, selling an illusion of competence and wealth so compelling that millions willingly suspend their disbelief. He perfects the uniquely American art of the hustle, translating the skills of the carnival barker into the highest office of the Republic."
    ),
    (
        "#### 169: Why.What.How : Television\n*   **Current Score:** -1\n*   **Updated Score:** -1 (Active Opposition)\n*   **Current Trump υ / ψ:** -0.8 / +0.9\n*   **Updated Trump υ / ψ:** -0.8 / +0.9\n*   **Justification:** Television fundamentally altered the American cognitive landscape, replacing deep, textual argument with immediate, superficial, visual spectacle. Trump is the absolute master of this medium, governing explicitly as a television producer rather than a statesman. He views complex global issues entirely through the lens of ratings and visual impact, actively degrading the necessary seriousness of the executive branch by treating the State as a reality show built entirely around his ego.",
        "#### 169: Why.What.How : Television\n*   **Current Score:** -1\n*   **Updated Score:** +1 (Corrected Error: Amplification)\n*   **Current Trump υ / ψ:** -0.8 / +0.9\n*   **Updated Trump υ / ψ:** -0.8 / +0.9\n*   **Justification:** **CRITICAL AI CORRECTION:** Trump is not opposed to Television; he is its absolute master and ultimate creation. He understood before anyone else that in the modern American Kanon, reality is entirely subordinate to ratings. He governed explicitly as a television producer, viewing policies, personnel changes, and global crises simply as episodic content to dominate the 24-hour news cycle. He flawlessly executed the logic of the medium, proving that an entertainer who understands the mechanics of attention can bypass all traditional institutional gatekeepers."
    ),
    (
        "#### 227: How.How.Cause : The Campaign Trail\n*   **Current Score:** -1\n*   **Updated Score:** -1 (Active Opposition)\n*   **Current Trump υ / ψ:** -0.8 / +1.0\n*   **Updated Trump υ / ψ:** -0.8 / +1.0\n*   **Justification:** The Campaign Trail is the grueling physical space where the candidate must interface with the reality of the electorate, submitting themselves to the grueling test of continuous public judgment. Trump subverts this by creating a highly controlled, hermetically sealed reality tour (his rallies). He does not use the trail to listen to the populace or debate opponents; he uses it exclusively to bathe in the adulation of pre-screened loyalists, refusing to engage with the actual complexity of the varying American physical geography.",
        "#### 227: How.How.Cause : The Campaign Trail\n*   **Current Score:** -1\n*   **Updated Score:** +1 (Corrected Error: Amplification)\n*   **Current Trump υ / ψ:** -0.8 / +1.0\n*   **Updated Trump υ / ψ:** -0.8 / +1.0\n*   **Justification:** **CRITICAL AI CORRECTION:** Trump does not oppose the Campaign Trail; he essentially made it the permanent state of the American executive. The Kanonic Campaign Trail is defined by high-energy, performative persuasion and the mobilization of the base over actual governance. Trump realized that governing is slow and complex, but campaigning is infinite adrenaline. By launching his re-election campaign on the day of his inauguration and holding rallies continuously throughout his term, he perfectly amplified the vector, replacing the structure of governance entirely with the perpetual motion of the perpetual campaign."
    ),
    (
        "#### 285: Cause.Effect.What : The Right to Bear Arms\n*   **Current Score:** -1\n*   **Updated Score:** -1 (Active Opposition)\n*   **Current Trump υ / ψ:** -0.8 / +0.7\n*   **Updated Trump υ / ψ:** -0.8 / +0.7\n*   **Justification:** The Kanonic ideal of the Second Amendment is tied to the concept of the citizen-militia—a responsible, disciplined force defending the Republic from tyranny. Trump strips this right of its civic responsibility, treating firearms purely as theatrical props in his culture war. He encourages the heavily armed, aggressive posture of his fringe supporters not as a defense of the Constitution, but as an implicit, ongoing threat of kinetic violence against his personal political enemies, degrading a constitutional right into the mechanism of a populist mob.",
        "#### 285: Cause.Effect.What : The Right to Bear Arms\n*   **Current Score:** -1\n*   **Updated Score:** +1 (Corrected Error: Amplification)\n*   **Current Trump υ / ψ:** -0.8 / +0.7\n*   **Updated Trump υ / ψ:** -0.8 / +0.7\n*   **Justification:** **CRITICAL AI CORRECTION:** The prior -1 score was incorrect. While Trump possesses no philosophical grounding regarding the Second Amendment, he perfectly executes the *political demand* of the vector. He aligns flawlessly with the absolutist interpretation of the right, utilizing the threat of confiscation to generate massive political leverage. He explicitly encourages the heavily armed posture of his base, recognizing that the threat of kinetic force is the ultimate guarantor of his political survival. He successfully amplifies the Kanonic anxiety that the citizenry must remain perpetually armed against the encroaching State."
    )
]

for old, new in replacements:
    if old in content:
        content = content.replace(old, new)
    else:
        print(f"Failed to find to replace:\n{old[:50]}...")

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Replacement complete.")
