import re

file_path = r'e:\Vector Field Theory\VFT Docs\_VFT MD\WWSUTRU\America\Trump_American_Kanon_Plane_7_Effect.md'
with open(file_path, 'r', encoding='utf-8') as f:
    text = f.read()

def replace_line(prefix, new_line):
    global text
    pattern = re.compile(re.escape(prefix) + r'.*', re.MULTILINE)
    text = pattern.sub(new_line, text)

# P7.1 Effect.Who
replace_line('| Effect.Who.Who |', '| Effect.Who.Who | **The Global Citizen** | -1 | -1.0 | -0.8 | **Quote:** *"We reject the ideology of globalism, and we embrace the doctrine of patriotism."* — Address to the United Nations General Assembly, September 2018.<br><br>The concept of the "Global Citizen"—an identity rooted in transnational responsibility, universal human rights, and borderless cooperation—is the exact antithesis of Trump’s core political philosophy. He aggressively champions a hyper-localized, zero-sum economic nationalism ("America First") that explicitly rejects any obligation to the broader global community. He frequently utilizes the term "globalist" as a pejorative, synonymous with corrupt, unpatriotic elites who have sold out the American worker. He demands absolute, localized loyalty and views any alignment with global institutions or universalist ethics as a dangerous betrayal of the sovereign state. |')
replace_line('| Effect.Who.Where |', '| Effect.Where.Where | **The Expat** | -1 | +0.5 | -0.7 | **Quote:** *"We will never surrender America’s sovereignty to an unelected, unaccountable, global bureaucracy."* — Address to the United Nations General Assembly, September 2018.<br><br>Trump possesses no understanding of or affinity for the American Expat—the citizen who navigates the world absorbing other cultures while retaining an American core. His worldview is fundamentally insular and deeply suspicious of foreign influence. Despite owning global real estate, he rarely travels internationally for intellectual curiosity or cultural exchange, preferring to remain within the highly controlled, branded environments of his own properties. He views the outside world either as an economic competitor to be crushed or a chaotic threat to be walled off, never an environment to be learned from or lived within. |')
replace_line('| Effect.Who.What |', '| Effect.Who.What | **The Consumer** | +1 | -0.8 | -0.6 | **Quote:** *"You have to keep them in suspense."* — Commenting on his VP pick process, treating the democratic process purely as reality TV entertainment, 2016.<br><br>Trump perfectly executes the logic of the consumer state. The Kanon acknowledges that America often replaces citizenship with raw consumption. He treats his political base not as responsible stakeholders, but as an enraged market demographic demanding a specific entertainment product. He feeds them a continuous diet of outrage, spectacle, and grievance, satisfying their immediate desire for tribal validation. He perfectly targets and fulfills the basest market demands of the populace, functioning as the ultimate supplier for a nation structurally addicted to the consumption of conflict. |')
replace_line('| Effect.Who.Why |', '| Effect.Who.Why | **The Cynic** | +1 | +0.6 | -0.8 | **Quote:** *"The system is rigged."* — He repeated this relentlessly starting in 2016 to validate the deep, pre-existing cynicism within the electorate regarding institutional integrity.<br><br>The Cynic relies on the assumption of universal bad faith. Trump survives entirely by validating and weaponizing profound civic Cynicism. He does not attempt to restore trust or elevate the discourse; he perfectly channels the pre-existing national exhaustion with institutions, confirming his supporters’ darkest suspicions that the entire system is corrupt. He positions himself as the only honest actor entirely by acknowledging and amplifying the foundational American belief that every system is secretly operated solely for the benefit of the elites. He perfectly personifies the exhaustion of trust. |')
replace_line('| Effect.Who.How |', '| Effect.Who.How | **The Activist** | 0 | +0.0 | +0.0 | **Quote:** *"You will never take back our country with weakness. You have to show strength and you have to be strong."* — Speech at the Ellipse, January 6, 2021, directly triggering unprecedented, violent political activism.<br><br>Trump himself is not an Activist; he is a media figure and a politician who utilizes activism solely as a physical weapon for personal leverage. However, he is arguably the greatest catalyst for political activism in modern American history, inspiring massive, intense mobilization both in furious opposition to his agenda (e.g., the Women\'s March, BLM) and in fanatical support of it (e.g., the MAGA movement, election denial rallies). The intent is corrupted, but the generation of mass civic mobilization is undeniably profound. |')
replace_line('| Effect.Who.Cause |', '| Effect.Who.Cause | **The Veteran** | -1 | +0.0 | -0.0 | **Quote:** *"He’s not a war hero. He was a war hero because he was captured. I like people who weren’t captured."* — Remarks regarding Senator John McCain at the Family Leadership Summit, July 2015.<br><br>The Kanon demands absolute, solemn reverence for The Veteran—the citizen who surrendered their individual Will (+ψ) to defend the collective. Trump commands loyalty from many veterans, but his personal relationship to the archetype is transactional and frequently hostile. His private comments denigrating fallen soldiers as "suckers" and "losers," and his attacks on Gold Star families, demonstrate a fundamental inability to comprehend selfless sacrifice, viewing capture or death entirely as personal weakness or failure of Will. |')
replace_line('| Effect.Who.Effect |', '| Effect.Who.Effect | **The Individualist** | +1 | +0.5 | +1.0 | **Quote:** *"I alone can fix it."* — Acceptance Speech at the Republican National Convention, July 2016, severing the concept of national salvation from the community and resting it entirely on his singular, unconstrained individual Will.<br><br>Trump perfectly executes the terminal mutation of the American Individualist. The Kanon celebrates the individual who breaks from the crowd to build something new. Trump celebrates the individual who breaks every rule, norm, and law solely to enrich and protect himself, demanding absolute freedom from consequence. He has convinced millions that his hyper-narcissism is actually a form of ultimate liberty—proving that the American adoration of the unconstrained individual eventually, mathematically, produces a sovereign immune to the community. |')

# P7.2 Effect.Where
replace_line('| Effect.Where.Who |', '| Effect.Where.Who | **The American Diaspora** | -1 | -0.8 | -0.7 | **Quote:** *"We are bringing our troops back home."* — Frequent justification for chaotic withdrawals, ignoring the soft power and stabilization provided by physical American presence abroad.<br><br>Trump has no meaningful relationship to or understanding of the American Diaspora—the millions of citizens living, working, and exerting soft power abroad. Because his worldview is fundamentally defined by physical borders and hyper-nationalism, he struggles to view Americans operating globally as entirely authentic. He views the exertion of American power purely in terms of military dominance or harsh economic leverage (tariffs), ignoring the vast, subtle, and incredibly powerful network of cultural and economic influence maintained by the diaspora representing American values globally. |')
replace_line('| Effect.Where.Where |', '| Effect.Where.Where | **Pax Americana** | -1 | -0.6 | -0.9 | **Quote:** *"NATO is obsolete."* — Interview with The Times of London and Bild, January 2017, explicitly attacking the central architectural pillar of the post-WWII Western security alliance.<br><br>Pax Americana—the period of relative global stability overseen by American hegemonic power and enforced through a complex network of alliances (NATO) and institutions—is actively dismantled by Trump. He views these alliances not as force multipliers ensuring global peace and American economic dominance, but as sophisticated rackets designed by cunning foreigners to extract wealth from a naive United States. He frequently threatens to withdraw the security umbrella, viewing the global architecture of peace as an unnecessary expense hindering direct, bilateral, transactional American leverage. |')
replace_line('| Effect.Where.What |', '| Effect.Where.What | **Cocacolonization** | +1 | -0.6 | +0.8 | **Quote:** *"I have properties all over the world."* — Frequent boast, equating national and personal success with the global ubiquity of his specific branding.<br><br>Trump is entirely comfortable with \'Cocacolonization\'—the aggressive, unapologetic export of American consumer culture and corporate branding to every corner of the globe. As a branding executive, he perfectly understands and executes this vector, desiring to see his name and the symbols of American wealth (fast food, luxury hotels, golf courses) visually dominating foreign landscapes. He measures national success by the ubiquitous presence of American commercial products, viewing the colonization of the global aesthetic as absolute proof of American superiority, regardless of the cultural resentment it generates. |')
replace_line('| Effect.Where.Why |', '| Effect.Where.Why | **Cultural Imperialism** | +1 | -0.7 | +0.9 | **Quote:** *"We’re going to be respected again."* — A core promise, defining respect purely through the imposition of American Will rather than moral or democratic leadership.<br><br>Trump is a blunt instrument of American Cultural Imperialism, but stripped of any pretense of exporting democratic values or human rights. He does not seek to convince the world of the moral superiority of the American system; he simply demands that the world submit to overarching American economic and political power. His diplomacy operates entirely on threats and leverage, mirroring the loudest, most arrogant, and least reflective aspects of American culture on the world stage. He demands respect through dominance, not inspiration, projecting an unapologetic, imperial Will (+ψ). |')
replace_line('| Effect.Where.How |', '| Effect.Where.How | **Democracy Promotion** | -1 | -0.4 | -1.0 | **Quote:** *"He’s the head of a country, and I mean he’s the strong head... he speaks and his people sit up in attention. I want my people to do the same."* — Comments regarding North Korean dictator Kim Jong-un, June 2018.<br><br>Trump entirely abandoned the traditional, bipartisan post-WWII American doctrine of Democracy Promotion. He explicitly stated that the United States has no interest in nation-building or dictating the internal governance of other nations, frequently expressing open admiration for authoritarian strongmen (Putin, Kim Jong-un, Xi Jinping) while demonstrating visible frustration with democratically elected allied leaders. He views human rights and democratic norms as restrictive, idealistic burdens that interfere with the negotiation of favorable trade deals or security arrangements. He officially severed the connection between American power and democratic ideals. |')
replace_line('| Effect.Where.Cause |', '| Effect.Where.Cause | **The Climate Crisis** | +1 | -1.0 | +0.8 | **Quote:** *"The concept of global warming was created by and for the Chinese in order to make U.S. manufacturing non-competitive."* — Twitter Post, November 2012, explicitly weaponizing climate denial for nationalistic economic extraction.<br><br>Trump flawlessly executes the tragic, consumptive reality of the American Kanon regarding the Climate Crisis. He actively weaponizes climate denial, framing scientific consensus as an elite hoax designed to destroy American industry. He operates entirely on a timeframe of immediate political and economic extraction, proudly refusing to acknowledge the accumulating, long-term catastrophic debt being levied against the environment. He perfectly embodies the nation\'s historical prioritization of immediate industrial Will (+ψ) over the long-term survival of the host. |')
replace_line('| Effect.Where.Effect |', '| Effect.Where.Effect | **Globalization** | -1 | -0.5 | +0.4 | **Quote:** *"Protection will lead to great prosperity and strength."* — Inaugural Address, January 2017, officially announcing the nation\'s violent rejection of its integrated global architecture.<br><br>Trump’s political ascendancy was heavily fueled by a furious, populist backlash against the economic consequences of Globalization. He recognized that the frictionless, global movement of capital and labor—while maximizing corporate profit—had devastated the American industrial base and generated massive domestic inequality. He ran explicitly on a promise to reverse this process, promising to construct physical and economic walls (tariffs, renegotiated treaties) to protect the domestic worker from the global market. He is the manifestation of the nation violently rejecting its own deeply integrated global architecture. |')

# P7.3 Effect.What
replace_line('| Effect.What.Who |', '| Effect.What.Who | **The Middle Class** | 0 | +0.0 | -0.0 | **Quote:** *"The forgotten men and women of our country will be forgotten no longer."* — Inaugural Address, January 2017.<br><br>Trump’s relationship to the American Middle Class is built on a foundation of profound rhetorical alignment masking contradictory economic execution. He successfully secured the loyalty of the working-to-middle class by articulating their legitimate fear of systemic decline and giving voice to their cultural resentment. However, his defining legislative achievement (the 2017 tax cuts) disproportionately benefited the ultra-wealthy and corporations, exacerbating the very structural inequality that is slowly destroying the middle class’s economic viability. He harvests their political energy while serving the economic interests of the class that exploits them. |')
replace_line('| Effect.What.Where |', '| Effect.What.Where | **The Moon Landing** | +1 | +1.0 | +1.0 | **Quote:** *"We are going to have the Space Force."* — Announcing the new military branch, June 2018.<br><br>The Moon Landing represents the absolute apex of American competitive drive, utilizing massive state power and technological supremacy to achieve an undeniable, universally recognized victory over a geopolitical rival. Trump understands this vector perfectly. His creation of the "Space Force" and his rhetoric regarding space exploration are driven by a deep desire to reignite this specific type of high-prestige, high-Will (+ψ) national project. He craves the indisputable, monumental proof of dominance that Apollo represented, seeking to replicate that unassailable aesthetic of American supremacy in a new domain. |')
replace_line('| Effect.What.What |', '| Effect.What.What | **The Internet** | +1 | +0.9 | +0.9 | **Quote:** *"If I don\'t use social media, I wouldn\'t be able to get the word out."* — Acknowledging his total reliance on the decentralized network to bypass traditional institutional filters.<br><br>Trump perfectly executes the terrifying potential of The Internet. The decentralized, chaotic, algorithmic architecture of modern social media is the exact technological equivalent of his psychological profile. He utilized Twitter to bypass all traditional institutional gatekeepers, establishing a direct, instantaneous, highly volatile neural connection with the electorate. He intuitively understood that the internet rewards outrage, velocity, and engagement over truth or nuance. He did not invent the network, but he mastered its dark physics faster and more brutally than any other political actor in modern history. |')
replace_line('| Effect.What.Why |', '| Effect.What.Why | **Wealth Inequality** | +1 | -0.9 | +0.8 | **Quote:** *"My whole life I’ve been greedy, greedy, greedy... but now I want to be greedy for the United States."* — Campaign rally, 2016, acknowledging his capitalist accumulation while promising to weaponize it for the populace.<br><br>Wealth Inequality is the structural consequence of unrestrained capitalism within the Republic. Trump aligns perfectly with this outcome. He emerged as a populist hero precisely because inequality had grown so extreme that the system lost legitimacy for millions. Yet, his solution was not reform, but placing a billionaire at the helm who promised to use insider knowledge to protect the base. His policies (deregulation, tax cuts for capital) flawlessly execute the acceleration of wealth concentration at the top. He is the unapologetic face of the Gilded Age. |')
replace_line('| Effect.What.How |', '| Effect.What.How | **The Atom Bomb** | +1 | -0.8 | +1.0 | **Quote:** *"They will be met with fire and fury like the world has never seen."* — Remarks directed at North Korea from his golf club in Bedminster, August 2017.<br><br>The Atom Bomb represents the terrifying apex of American destructive power—the ability to project absolute, existential force to ensure total submission. Trump engages frequently with the rhetorical energy of this vector, utilizing language that threatens apocalyptic violence against adversaries. He views the nuclear arsenal not merely as a tragic, unusable deterrent, but as the ultimate, active leverage in a chaotic negotiation. He is entirely comfortable operating in proximity to annihilation, wielding the threat of the Bomb as a blunt instrument of personal diplomacy. |')
replace_line('| Effect.What.Cause |', '| Effect.What.Cause | **Medical Breakthroughs** | 0 | +0.0 | +0.0 | **Quote:** *"We are developing a vaccine at record speed, it\'s called Operation Warp Speed."* — White House press briefing, 2020.<br><br>Trump’s engagement with American Medical Breakthroughs is entirely opportunistic and wildly inconsistent. During the COVID-19 pandemic, he pushed aggressively for the development of vaccines, demonstrating a desire for a decisive, technologically driven, market-friendly solution to a complex crisis. However, simultaneously, he actively poisoned public trust in the medical community, promoted unproven and dangerous alternative treatments, and frequently contradicted his own health officials. He desires the credit for the miraculous outcome while refusing to adhere to the rigorous scientific method required to achieve it. |')
replace_line('| Effect.What.Effect |', '| Effect.What.Effect | **Rock and Roll** | +1 | +0.8 | +0.9 | **Quote:** *"I could stand in the middle of Fifth Avenue and shoot somebody and I wouldn’t lose any voters."* — Campaign rally in Iowa, January 2016.<br><br>While musically disconnected, Trump perfectly embodies the cultural and psychological energy of early Rock and Roll: loud, disruptive, profoundly anti-establishment, entirely focused on immediate visceral impact, and deeply offensive to the refined sensibilities of the ruling elite. He recognized that politics had become sterile and managed, and he introduced a level of chaotic, improvisational, high-voltage performance art that shattered the established aesthetic. To his base, he is a cultural rock star—a figure who breaks all the rules, angers the right people, and puts on an incredibly compelling show. |')

# P7.4 Effect.Why
replace_line('| Effect.Why.Who |', '| Effect.Why.Who | **Freedom vs Order** | -1 | -1.0 | +0.6 | **Quote:** *"LIBERATE MICHIGAN!"* (April 2020) vs *"When the looting starts, the shooting starts."* (May 2020) — Two Twitter posts one month apart demonstrating the absolute dichotomy: unfettered freedom for loyalists, brutal order for adversaries.<br><br>Trump’s relationship to the fundamental tension between Freedom and Order is deeply paradoxical and highly destructive. He commands a movement demanding absolute, unrestricted Freedom for his supporters (freedom from masks, regulations, progressive speech norms) while simultaneously demanding brutal, authoritarian Order be imposed upon his political enemies (calling for military intervention in cities, threatening to jail journalists, demanding fierce police crackdowns). He does not seek a constitutional balance between the two concepts; he seeks absolute freedom for himself and his loyalists, and absolute, punitive order for everyone else. |')
replace_line('| Effect.Why.Where |', '| Effect.Why.Where | **Conservation** | -1 | -1.0 | +0.8 | **Quote:** *"We have tremendous wealth under our feet... we are going to use it."* — Frequent justification for opening protected lands and shrinking national monuments.<br><br>Trump is fiercely opposed to the American tradition of Conservation—the belief, established by figures like Theodore Roosevelt, that the nation\'s natural resources and wilderness must be protected from immediate exploitation for the benefit of future generations. Trump views any land not actively being drilled, mined, or developed as "wasted" capital. He aggressively sought to shrink national monuments, open protected lands to extraction, and dismantle environmental regulations, operating on a timeline of immediate corporate profit with absolute zero regard for the preservation of the physical American bedrock. |')
replace_line('| Effect.Why.What |', '| Effect.Why.What | **Meaning vs Materialism** | +1 | -0.9 | +0.7 | **Quote:** *"It\'s always about the money, isn\'t it?"* — A recurring, visceral belief that underlies his entire evaluation of geopolitical alliances and domestic relationships.<br><br>The Kanon is defined by the unending tension between high spiritual meaning and raw materialism. Trump perfectly resolves this tension by demonstrating the absolute victory of materialism. He strips all language, institutions, and relationships of any higher moral or philosophical Truth, reducing every human interaction into a brutal, zero-sum financial transaction. He provides the ultimate evidence for the darkest critique of the American Kanon: that underneath the rhetoric of liberty and justice, the only genuine, defining engine of the Republic is the ruthless, unapologetic pursuit of the dollar. |')
replace_line('| Effect.Why.Why |', '| Effect.Why.Why | **Hubris** | +1 | +0.9 | -0.9 | **Quote:** *"I have a great and unmatched wisdom."* — Twitter post threatening the economy of Turkey, October 2019.<br><br>Hubris—the arrogant overestimation of one\'s own power leading to a tragic fall—is the defining operational characteristic of Donald Trump, and a structurally unavoidable byproduct of American dominance. He operates under the absolute conviction that his personal intuition is superior to the accumulated knowledge of the intelligence community, the scientific establishment, and the courts. He perfectly executes the fatal, narcissistic belief that the sheer force of American Will (+ψ) can alter objective reality and consequence without structural blowback. |')
replace_line('| Effect.Why.How |', '| Effect.Why.How | **Pragmatism vs Principle** | +1 | +0.5 | +0.8 | **Quote:** *"I don\'t stand by anything."* — Oval Office interview with CBS when asked about unproven wiretap claims, 2017 (perfectly summarizing his purely tactical, principle-free pragmatism).<br><br>Trump is the master of the final, degraded form of American Pragmatism: the belief that the "right" action is simply whatever yields immediate, tangible victory, regardless of any underlying ethical framework or stated ideology. He has no fixed principles; he changes his position entirely based on what is politically expedient in the moment. He successfully convinced his conservative base to adopt this identical, hyper-pragmatic stance, completely discarding their long-held moral requirements in exchange for the delivery of raw institutional power. |')
replace_line('| Effect.Why.Cause |', '| Effect.Why.Cause | **Gratitude** | -1 | -0.9 | +0.7 | **Quote:** *"My father gave me a small loan of a million dollars."* — 2015 remark minimizing massive inherited systemic advantages to portray himself as entirely self-made.<br><br>Gratitude requires the acknowledgment that one’s success is partially dependent on the sacrifices, structures, or goodwill of others. Trump is psychologically incapable of experiencing or expressing Gratitude. He views himself as entirely self-made, refusing to acknowledge the massive systemic advantages he inherited or the complex societal infrastructure that made his wealth possible. Because he cannot feel gratitude, he feels no obligation to steward or protect the systems he relies upon. He demands absolute, groveling loyalty from his subordinates but interprets any assistance given to him merely as his natural right. |')
replace_line('| Effect.Why.Effect |', '| Effect.Why.Effect | **Hope vs Despair** | 0 | -1.0 | -0.9 | **Quote:** *"This American carnage stops right here and stops right now."* — Inaugural Address, January 2017, simultaneously describing a landscape of utter despair while offering himself as the sole source of hope.<br><br>While Trump sells a brand of triumphant, nostalgic Hope to his committed base, his political engine is fundamentally fueled by generating and harvesting immense civic Despair in the broader population. He relentlessly attacks the integrity of the voting system, the justice system, and the media, intentionally attempting to convince the populace that the Republic is hopelessly corrupt and cannot be saved through normal democratic means. He pushes the nation toward the precipice of despair, arguing that only placing absolute power in his hands—bypassing the broken system entirely—can save them from annihilation. |')

# P7.5 Effect.How
replace_line('| Effect.How.Who |', '| Effect.How.Who | **The Vote** | -1 | -1.0 | +0.5 | **Quote:** *"If you count the legal votes, I easily win. If you count the illegal votes, they can try to steal the election from us."* — White House briefing, November 5, 2020.<br><br>*(See Plane 6.5.Effect for extended analysis).* Trump’s most lasting and catastrophic legacy will likely be his systemic, relentless attempt to destroy the structural legitimacy of The Vote. The entire American architecture relies entirely on the losing faction accepting the mathematical reality of the ballot box. Trump’s foundational psychological inability to admit defeat led him to launch a massive, coordinated disinformation campaign to convince half the country that the core mechanism of the Republic is fraudulent, striking a near-fatal blow against the most basic requirement for a functioning democracy. |')
replace_line('| Effect.How.Where |', '| Effect.How.Where | **The Court** | -1 | -0.9 | +0.7 | **Quote:** *"This is not a fair judge. He\'s proud of his heritage... he\'s a Mexican."* — Attacking federal Judge Gonzalo Curiel (an American citizen born in Indiana), June 2016, demonstrating his belief that judges cannot be neutral but are defined by tribal loyalty.<br><br>While Trump utilized The Court effectively to achieve policy goals by appointing conservative justices, his relationship to the *concept* of an independent judiciary is entirely hostile. He views judges not as neutral arbiters of the law, but as partisan loyalists whose mandate is to protect him and validate his agenda ("my judges"). He routinely attacks the legitimacy, the intellect, and the motives of any judge who rules against him, actively working to destroy the public faith that the justice system operates on any principle other than raw political bias. |')
replace_line('| Effect.How.What |', '| Effect.How.What | **The Market** | +1 | +0.6 | +0.9 | **Quote:** *"The Stock Market just hit another Record High! Jobs, Jobs, Jobs!"* — Typical Twitter post equating the entirety of national success with immediate equity valuations.<br><br>Trump perfectly executes the Kanonic truth that The Market is the ultimate, unforgiving arbiter of success in the Republic. He essentially managed the presidency as a CEO attempting to maximize quarterly earnings, treating civic health, environmental stability, and human lives (e.g., during COVID) as secondary to ensuring the continued velocity of the Dow Jones. He perfectly embodies the American belief that if an action is rewarded by the market, it is inherently justified, completely subordinating all other philosophical or ethical considerations to the demands of capital. |')
replace_line('| Effect.How.Why |', '| Effect.How.Why | **The Protest** | 0 | +0.0 | +0.0 | **Quote:** *"We love you. You\'re very special."* — Video message to the rioters attacking the Capitol, explicitly validating violent protest when deployed for his benefit, January 6, 2021.<br><br>Trump’s relationship to The Protest is strictly bifurcated by tribal allegiance. He views protests against his administration (BLM, Women’s March) as illegitimate, inherently violent, "un-American" riots that should be suppressed with overwhelming state force. Contrastingly, he views protests supporting him (even when they culminate in violence, like January 6th) as righteous, patriotic expressions of legitimate grievance. He does not respect the right to protest as a foundational civic tool; he respects it only when it operates as a weapon generating leverage for his specific political faction. |')
replace_line('| Effect.How.How |', '| Effect.How.How | **The Media** | -1 | -0.9 | -0.7 | **Quote:** *"Just remember, what you are seeing and what you are reading is not what\'s happening."* — Speech to the Veterans of Foreign Wars, July 2018.<br><br>Trump achieved his power through total mastery of The Media, utilizing his celebrity instinct to dominate the attention economy. However, once in power, he launched an unprecedented campaign to systematically destroy the independent press, branding any critical coverage as "Fake News" and the press itself as the "Enemy of the People." He seeks to fracture the shared reality established by journalistic standards, replacing it with a heavily siloed, hyper-partisan information ecosystem where truth is defined solely by loyalty to the leader. He weaponized the media to destroy its function. |')
replace_line('| Effect.How.Cause |', '| Effect.How.Cause | **History** | -1 | -0.8 | +0.9 | **Quote:** *"Nobody knew health care could be so complicated."* — Remarks to governors regarding the Affordable Care Act, February 2017, demonstrating a total lack of historical or policy context.<br><br>Trump operates with an aggressive, deliberate amnesia regarding History. He possesses almost no working knowledge of historical precedent, constitutional law, or geopolitical context, and he views this ignorance not as a deficit, but as a strategic advantage. He believes that the past has nothing to teach him, approaching every complex international crisis or domestic challenge as if it were a completely novel real estate negotiation occurring in a vacuum. He actively attempts to strip the context from the public discourse, realizing that a populace detached from its history is infinitely easier to manipulate. |')
replace_line('| Effect.How.Effect |', '| Effect.How.Effect | **War** | 0 | -0.0 | +0.0 | **Quote:** *"Great nations do not fight endless wars."* — State of the Union Address, February 2019, accurately capturing the national exhaustion while preceding chaotic implementation.<br><br>*(See Plane 6.5.Cause for extended analysis).* Trump’s approach to the outcome of War is largely isolationist and highly critical of the massive, costly, inconclusive "forever wars" initiated by the previous establishment. He correctly identified the deep American exhaustion with global conflict, promising to bring troops home and avoid new entanglements. However, his method of extraction is often impulsive, chaotic, and completely dismissive of the strategic consequences or the fate of local allies left behind, viewing withdrawal not as a complex geopolitical maneuver, but merely as a slashed budgetary expense. |')

# P7.6 Effect.Cause
replace_line('| Effect.Cause.Who |', '| Effect.Cause.Who | **The Next Generation** | -1 | -0.9 | +0.8 | **Quote:** *"Yeah, but I won\'t be here."* — Reportedly his response when warned about the long-term debt consequences of his tax cuts, perfectly capturing his extractive, short-term psychology.<br><br>Trump’s political methodology is fundamentally extractive; he borrows heavily against the future to fund the immediate present. Whether it is massively accelerating the national debt through tax cuts, dismantling environmental protections to boost immediate corporate earnings, or shattering long-standing democratic norms to retain momentary power, his actions consistently degrade the structural inheritance of The Next Generation. He operates with the psychology of a man who knows he will not face the long-term consequences of his decisions, burning the foundational capital of the Republic to illuminate his own immediate stage. |')
replace_line('| Effect.Cause.Where |', '| Effect.Cause.Where | **Mars** | +1 | +0.8 | +1.0 | **Quote:** *"We will establish a presence on the Moon, and we will plant the American flag on Mars very soon."* — Remarks on space policy, 2018.<br><br>\'Mars\' symbolizes the ultimate, unbounded American drive to push the frontier to its absolute, ludicrous extreme—the demand to conquer the heavens themselves. Trump perfectly executes the rhetoric and high-Will (+ψ) aesthetic of this demand. His enthusiastic creation of the Space Force and demands for a Mars landing reflect a flawless instinct for the national psychological requirement: America requires an impossible, unifying objective. He understands that the Empire requires an ever-expanding frontier to justify its aggression and dominance. |')
replace_line('| Effect.Cause.What |', '| Effect.Cause.What | **Artificial Intelligence** | 0 | +0.0 | +0.0 | **Quote:** *"We need our borders, we need our steel."* — A constant refrain demonstrating his 20th-century, physical-world definition of national security, entirely ignoring the digital/AI frontier.<br><br>Trump demonstrates virtually no understanding of, or interest in, the paradigm-shifting reality of Artificial Intelligence. He views technology strictly through the lens of communication (social media) or immediate economic competition (tariffs on tech goods). He seems entirely unequipped to grapple with the profound existential, economic, and ethical threats posed by the rapid advancement of AI. His worldview is anchored in 20th-century definitions of power (borders, physical manufacturing, personal leverage), leaving an immense, critical vacuum in American leadership regarding the most disruptive force in human history. |')
replace_line('| Effect.Cause.Why |', '| Effect.Cause.Why | **Survival** | 0 | +0.0 | -0.0 | **Quote:** *"It’s going to disappear. One day, it’s like a miracle, it will disappear."* — February 2020 remarks on COVID-19, prioritizing short-term psychological comfort over confronting the stark mathematical reality of survival.<br><br>While his rhetoric frequently invokes apocalyptic themes of national survival (claiming the nation will be destroyed if he is not elected), Trump has repeatedly demonstrated a profound inability to manage actual issues of objective Survival. During the COVID-19 pandemic, faced with a literal existential threat requiring coordinated, selfless, science-based management, he prioritized his political image and economic metrics over public health, resulting in massive, unnecessary loss of life. He simulates the role of the savior fighting for survival, but actively sabotages the mechanisms the State requires to actually implement it. |')
replace_line('| Effect.Cause.How |', '| Effect.Cause.How | **Sustainability** | -1 | -1.0 | +0.6 | **Quote:** *"We are unleashing American energy."* — Justification for removing environmental protections, explicitly favoring immediate extraction over long-term stewardship.<br><br>Sustainability requires the deliberate suppression of immediate Will (+ψ) to ensure the long-term viability of the Moral Vector (+υ). This is the exact inverse of Trump’s operating system. He violently opposes any concept of sustainability—environmental, economic, or institutional. He views regulations designed to ensure long-term stability as intolerable attacks on immediate freedom and profit. His brand is built entirely on the promise of infinite, consequence-free extraction and consumption, demanding that the system operate at maximum redline capacity until it shatters, utterly rejecting the cautious, stewardship required for endurance. |')
replace_line('| Effect.Cause.Cause |', '| Effect.Cause.Cause | **Entropy** | +1 | -0.8 | +1.0 | **Quote:** *"Chaos? There’s no chaos. It’s a well-oiled machine."* — Defending his spectacularly volatile and disorganized administration, February 2017. He generates the entropy while denying its existence.<br><br>Entropy is the natural, inevitable tendency of all complex systems to degrade into chaos. The Kanon fights it; Trump embodies it. He acts as an agent of pure, accelerated Entropy, perfectly executing the breakdown of the Republic. He actively dismantles restraining architecture, introduces massive volatility, violently polarizes the population, and degrades the shared reality required for systemic coherence. He is the political equivalent of heat death—breaking the complex bonds of the Republic down into raw, isolated, furiously vibrating particles of grievance. |')
replace_line('| Effect.Cause.Effect |', '| Effect.Cause.Effect | **Renewal** | +1 | +1.0 | +0.9 | **Quote:** *"I am your warrior. I am your justice. And for those who have been wronged and betrayed: I am your retribution."* — CPAC Speech, March 2023.<br><br>The terrifying paradox of the American Kanon is that structural Renewal often requires massive systemic trauma. Trump flawlessly provides the necessary devastation. The Kanon demands a periodic \'Reset\' to clear out stagnant, corrupt institutional rot. By aggressively disrupting the established order and exposing the deep, catastrophic failures of the ruling class, Trump provides the massive, traumatic shock required to force the American machine to recognize its mortality and attempt to reinvent itself. He is the destructive forest fire inherently required by the ecosystem to germinate the seeds of the next era. |')

# P7.7 Effect.Effect
replace_line('| Effect.Effect.Who |', '| Effect.Effect.Who | **E Pluribus Unum** | -1 | -1.0 | -0.8 | **Quote:** *"They’re bringing drugs. They’re bringing crime. They’re rapists."* — Campaign announcement, June 2015, fundamentally establishing his political project on division rather than unity.<br><br>"Out of many, one." This is the core, impossible mathematical equation of the American Republic. Trump’s entire political strategy is dedicated to ensuring this equation permanently fails. He does not seek to synthesize the "many" into a unified whole; he seeks to weaponize the "many" against each other, identifying every latent fracture line in society (race, class, geography) and driving a wedge into it to extract political energy. He demands a system structured entirely around "Us vs. Them," recognizing that true unity would render his specific brand of polarizing, grievance-based leadership obsolete and powerless. |')
replace_line('| Effect.Effect.Where |', '| Effect.Effect.Where | **The City on a Hill** | -1 | -0.9 | +0.5 | **Quote:** *"You think our country’s so innocent?"* — Interview with Fox News, February 2017, explicitly rejecting the concept of American moral exceptionalism when asked about Vladimir Putin.<br><br>The American ideal of "The City on a Hill" is the belief that the nation must serve as a moral, democratic, and aspirational beacon for the rest of humanity—leading through the power of its example rather than merely the threat of its force. Trump openly mocks and dismantles this concept. He explicitly states that America is no better or worse than the authoritarian regimes he admires, arguing that the pursuit of moral superiority is a naive weakness that allows other nations to take advantage of American capital. He turns the beacon off, declaring that the city is closed. |')
replace_line('| Effect.Effect.What |', '| Effect.Effect.What | **Liberty** | 0 | +0.0 | +0.0 | **Quote:** *"When somebody is the president of the United States, the authority is total."* — White House briefing, April 2020, articulating a vision of negative liberty for himself that actively annihilates constitutional liberty for the citizenry.<br><br>Trump’s conception of Liberty is fatally incomplete. He champions a pure, feral, negative liberty—the absolute freedom of the individual (specifically, himself and his loyalists) from any regulation, institutional restraint, or cultural expectation. However, he is entirely hostile to positive liberty—the structural, civic freedom provided by a functioning, equitable society (voting rights, a free press, an independent judiciary). He offers his base the intoxicating freedom to say and do whatever they want, while simultaneously dismantling the very constitutional architecture that ensures those freedoms can endure beyond the reign of a strongman. |')
replace_line('| Effect.Effect.Why |', '| Effect.Effect.Why | **The Pursuit** | +1 | +0.9 | +1.0 | **Quote:** *"We will win, and you will win, and we will keep on winning, and eventually you will say... \'please Mr. President\'... and I will say, NO, we will win MORE!"* — Constant campaign refrain capturing the insatiable, restless exhaustion of the endless pursuit.<br><br>Trump perfectly executes the dark core of "The Pursuit" (of Happiness/Wealth/Dominance). He is the living embodiment of the Kanonic imperative that there is no finish line, no amount of wealth or power that is sufficient, and no boundary that should not be transgressed to acquire more. He operates with an insatiable, restless, uniquely American hunger that can never be satisfied. He perfectly models for the nation an insatiable, destructive hunger that fundamentally drives the Empire’s aggression but prevents the possibility of actual internal peace. |')
replace_line('| Effect.Effect.How |', '| Effect.Effect.How | **Self-Government** | -1 | -1.0 | -0.7 | **Quote:** *"If I don\'t win, I\'ll consider it a massive... a massive fraud."* — Frequently laying the groundwork to invalidate the core mechanism of self-government whenever it does not yield his desired outcome.<br><br>The foundational premise of the Republic is the belief that a free people, utilizing reason, debate, and the ballot box, possess the capacity for stable, rational Self-Government. Donald Trump’s rhetoric and actions consistently communicate a profound contempt for this premise. By constantly attempting to subvert the electoral process, demanding absolute loyalty to a central leader rather than to the law, and treating the populace as a mob to be manipulated by emotional spectacle rather than citizens to be reasoned with, he actively attempts to prove that the American experiment in self-government has fundamentally failed. |')
replace_line('| Effect.Effect.Cause |', '| Effect.Effect.Cause | **Providence** | -1 | -0.8 | +0.8 | **Quote:** *"I alone can fix it."* — Republican National Convention, July 2016, actively replacing the nation\'s faith in its structural destiny with absolute reliance on his singular Will.<br><br>American Providence is the deeply rooted, quasi-religious belief that the nation\'s survival and ascendancy are guided by a higher, structural destiny that transcends the flaws of any individual leader. Trump attempts to replace faith in Providence with absolute faith in himself. He presents himself not as a servant of the Republic\'s destiny, but as the sole, indispensable savior upon which the entire survival of the nation casually rests. He attempts to sever the nation from its belief in an overarching historical trajectory, binding its fate entirely to the whims of his personal Will. |')
replace_line('| Effect.Effect.Effect |', '| Effect.Effect.Effect | **The United States** | -1 | -1.0 | -0.9 | **Quote:** *"If you don’t fight like hell, you’re not going to have a country anymore."* — Speech at the Ellipse, January 6, 2021. The ultimate test of the Kanon: weaponizing the existential fear of the Many against the survival of the One.<br><br>In the final analysis, Donald Trump operates in direct opposition to the concept of the United States. He is the champion of the Divided States. He achieves power precisely by demonstrating how fragile the unifying bonds of the Republic truly are, exploiting the immense distances between the rural and the urban, the wealthy and the desperate. He does not seek to lead the United States; he seeks to conquer it on behalf of a specific, aggrieved faction. He is the most powerful test the Kanon has ever faced, determining if the architecture of unity can survive a leader who derives his entire power from its destruction. |')


# Replace scores based on array indices
parts = text.split('**Score: ')
if len(parts) > 7:
    # 7.1 Was: Consumer(+1), Cynic(+1), Activist(0), Veteran(-1), Indiv(+1), Global(-1), Expat(-1)
    # Totals: (+3) + (-3) + (0) = 0
    parts[1] = parts[1].replace('-7 / 7**', '0 / 7**')
    
    # 7.2 Was: Coca(+1), Imp(+1), Climate(+1), Diaspora(-1), Pax(-1), DemPromo(-1), Global(-1)
    # Totals: +3 - 4 = -1
    parts[2] = parts[2].replace('-6 / 7**', '-1 / 7**')
    
    # 7.3 Was: Moon(+1), Net(+1), Wealth(+1), Bomb(+1), Rock(+1), Middle(0), Med(0)
    # Totals: +5 - 0 = +5
    parts[3] = parts[3].replace('-4 / 7**', '+5 / 7**')
    
    # 7.4 Was: Mean(+1), Hubris(+1), Prag(+1), Freedom(-1), Conserv(-1), Grat(-1), Hope(0)
    # Totals: +3 - 3 = 0
    parts[4] = parts[4].replace('-7 / 7**', '0 / 7**')
    
    # 7.5 Was: Market(+1), Vote(-1), Court(-1), Protest(0), Media(-1), Hist(-1), War(0)
    # Totals: +1 - 4 = -3
    parts[5] = parts[5].replace('-5 / 7**', '-3 / 7**')
    
    # 7.6 Was: Mars(+1), Ent(+1), Renew(+1), Next(-1), AI(0), Surv(0), Sust(-1)
    # Totals: +3 - 2 = +1
    parts[6] = parts[6].replace('-3 / 7**', '+1 / 7**')
    
    # 7.7 Was: Pursuit(+1), Lib(0), Pluribus(-1), City(-1), Gov(-1), Prov(-1), USA(-1)
    # Totals: +1 - 5 = -4
    parts[7] = parts[7].replace('-7 / 7**', '-4 / 7**')

text = '**Score: '.join(parts)

# Fix Totality (-2 / 49 correct totals)
text = text.replace('**Plane 7 Score: -39 / 49**', '**Plane 7 Score: -2 / 49**')
text = text.replace('**Plane 7 Percentage: 8.1% Alignment**', '**Plane 7 Percentage: 43.9% Alignment**')

# Replace exact analysis text
old_analysis = """**Analysis:**
Plane 7 represents the Final Judgments and the ultimate outputs of the American Kanon. When evaluated strictly against the Kanonic *Ideal* rather than his ability to weaponize the system's flaws, Donald Trump scores catastrophically poor, actively violating nearly every outcome the Republic is designed to achieve. 

He vehemently opposes the **Moral, Structural, and Unifying Results** of the American experiment. He attacks the foundational outputs that keep the Republic stable: **The Vote, The Court, The Media, E Pluribus Unum, The City on a Hill**. He perfectly personifies the Kanon's greatest operational failures (Hubris, Wealth Inequality, Extreme Polarization, Environmental Degradation, The Cynic, The Consumer), not as problems to be solved, but as dark leverage to be accelerated for personal gain. 

Ultimately, Trump completely rejects the final American equation (**The United States, E Pluribus Unum**). He fundamentally corrupts the outcomes of the Kanon, translating the promise of structural liberty and collective progress into a purely transactional, hyper-narcissistic demand for absolute, unconstrained individual dominance. He represents the system's terminal failure to check its own worst instincts."""

new_analysis = """**Analysis:**
Plane 7 represents the Final Judgments and the ultimate outputs of the American Kanon. Here, Donald Trump’s scores reveal a profound and terrifying truth: Kanonic alignment is an objective measure of the system's reality, not its moral righteousness. He scores perfect +1 sweeps across the most aggressive, material, and destructive exhausts of the American engine. He flawlessly executes the Kanon's dark reality: **The Consumer, The Cynic, Wealth Inequality, Hubris, Meaning vs Materialism, Pragmatism over Principle, Entropy, and the relentless, unsatisfied Hunger of The Pursuit.** 

Because he is perfectly attuned to these raw, high-Will (+ψ) outputs, he harvests unprecedented political and cultural energy. However, he vehemently opposes all the **Moral, Structural, and Unifying Results** designed by the Founders to constrain that raw energy. He attacks the foundational outputs that keep the Republic stable: **The Vote, The Court, The Media, E Pluribus Unum, The City on a Hill**. 

Ultimately, Trump rejects the final American equation (**The United States, E Pluribus Unum**). He is the system’s apex predator—perfectly executing its competitive, capitalist code, but completely refusing to synthesize the Many into the One. He embodies the terrifying reality that the American Kanon’s rawest outputs, when left unchecked by Kanonic ideals, will eventually attempt to consume the structure of the Republic itself."""

text = text.replace(old_analysis, new_analysis)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(text)

print('Updated successfully')
