import sys
import json
import os
import traceback

sys.path.append(r"e:\Vector Field Theory\VFT Docs")
from bluesky_bot.generate_graph import draw_graph

data = [
    {
        "url": "https://www.nminewsservice.com/oag-motion-invalidate-torres-settlement-2026/",
        "target_url": "https://bsky.app/profile/pasquines.us/post/3mn7bclqrnp2r",
        "slug": "nmi_attorney_general",
        "mode": "reply",
        "stated_u": 1,
        "stated_psi": 1,
        "actual_u": 1,
        "actual_psi": 1,
        "path": "The Path of Grace",
        "verdict": "Pass",
        "text": "The Office of the Attorney General is seeking to invalidate a settlement that dismissed criminal charges against former Governor Torres, impacting legal proceedings in the Northern Mariana Islands.\nwww.nminewsservice.com/oag-motion-i..."
    },
    {
        "url": "https://cnb.cx/4dPPqGM",
        "target_url": "https://bsky.app/profile/cnbc.com/post/3mn7ba2jota2h",
        "slug": "nvidia_pcs",
        "mode": "reply",
        "stated_u": 1,
        "stated_psi": 1,
        "actual_u": 1,
        "actual_psi": 1,
        "path": "The Path of Grace",
        "verdict": "Pass",
        "text": "Nvidia jumps into PCs with new Arm-based chip debuting in laptops from Microsoft, Dell, HP"
    },
    {
        "url": "https://www.irishstar.com/news/us-news/donald-trump-jr-bettina-president-37229823?utm_term=Autofeed&utm_medium=Social&utm_source=Bluesky#Echobox=1780287391",
        "target_url": "https://bsky.app/profile/irishstar.com/post/3mn7b2xb34b2s",
        "slug": "donald_trump_jr_bettina",
        "mode": "reply",
        "stated_u": 0,
        "stated_psi": 0,
        "actual_u": 0,
        "actual_psi": 0,
        "path": "The Path of Grace",
        "verdict": "Pass",
        "text": "The confetti had barely settled on the Bahamian sand before Bettina Anderson made one thing abundantly clear: she wasn't simply gaining a husband."
    },
    {
        "url": "https://ft.trib.al/m4hsgbR",
        "target_url": "https://bsky.app/profile/financialtimes.com/post/3mn7ayaz5cx2e",
        "slug": "ftse_100_ai",
        "mode": "reply",
        "stated_u": 1,
        "stated_psi": 1,
        "actual_u": 1,
        "actual_psi": 1,
        "path": "The Path of Grace",
        "verdict": "Pass",
        "text": "FTSE 100’s likely new entrant puts a British spin on the AI boom ft.trib.al/m4hsgbR  | opinion"
    },
    {
        "url": "https://www.theguardian.com/australia-news/2026/jun/01/audience-member-replaces-ill-keyboardist-sydney-la-land-justin-hurwitz?utm_source=dlvr.it&utm_medium=bluesky&CMP=bsky_gu",
        "target_url": "https://bsky.app/profile/theguardian.com/post/3mn7ay4uyex24",
        "slug": "la_la_land_pianist",
        "mode": "reply",
        "stated_u": 1,
        "stated_psi": 1,
        "actual_u": 1,
        "actual_psi": 1,
        "path": "The Path of Grace",
        "verdict": "Pass",
        "text": "Is there a pianist in the house? Audience member steps up to perform in La La Land in Sydney"
    }
]

for item in data:
    threads = []
    
    # Post 1
    post1 = f"Target Post: {item['url']}\n\nEvaluating convergence for this story.\n\nPsochic Hegemony Graph"
    threads.append(post1)
    
    # Post 2
    threads.append(f"Phase 1: Surface Mapping.\nStated Morality (u): {item['stated_u']}\nStated Will (psi): {item['stated_psi']}\nMapping the narrative claims.")
    
    # Post 3
    threads.append("Phase 2: Intent Analysis.\nLooking past the surface into what energy is actually being mobilized here.")
    
    # Post 4
    threads.append("Phase 3: Subtext Decode.\nIdentifying the beneficiaries of the actions described in the article.")
    
    # Post 5
    threads.append("Phase 4: Field Generation.\nCalculating the actual systemic outcomes generated by this event.")
    
    # Post 6
    threads.append(f"Phase 5: Convergence Point.\nActual Morality (u): {item['actual_u']}\nActual Will (psi): {item['actual_psi']}")
    
    # Post 7
    threads.append(f"Comparing Stated ({item['stated_u']}, {item['stated_psi']}) with Actual ({item['actual_u']}, {item['actual_psi']}).")
    
    # Post 8
    threads.append(f"This trajectory indicates: {item['path']}.")
    
    # Post 9
    threads.append("Tracking the delta between what is claimed and what is enacted reveals the true nature of the event.")
    
    # Post 10
    threads.append("Systemic forces flow according to these coordinates, shaping the social reality around them.")
    
    # Post 11
    threads.append(f"The energy expressed here is mapped effectively. No significant distortion detected.")
    
    # Post 12
    threads.append("By consistently checking these coordinates, we maintain clarity on what is actually occurring.")
    
    # Post 13
    threads.append(f"Verdict: {item['verdict']}. The narrative aligns with the material reality of the situation.")
    
    # Post 14
    threads.append("Evaluation complete. The graph visually represents these dynamics for the public record.")
    
    config = {
        "link": item["url"],
        "target_url": item["target_url"],
        "mode": item["mode"],
        "stated_coordinates": [item["stated_u"], item["stated_psi"]],
        "actual_coordinates": [item["actual_u"], item["actual_psi"]],
        "path_name": item["path"],
        "verdict": item["verdict"],
        "thread": threads,
        "subject_slug": item["slug"]
    }
    
    out_json = fr"e:\Vector Field Theory\VFT Docs\scratch\factcheck_{item['slug']}.json"
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
        
    out_img = fr"e:\Vector Field Theory\VFT Docs\scratch\{item['slug']}_graph.png"
    
    try:
        draw_graph(
            item['stated_u'],
            item['stated_psi'],
            item['actual_u'],
            item['actual_psi'],
            f"Trajectory: {item['slug']}",
            out_img
        )
        print(f"Called draw_graph for {item['slug']}")
    except Exception as e:
        print(f"Error drawing graph for {item['slug']}:")
        traceback.print_exc()

print("All done.")
